# -*- coding: utf-8 -*-
"""Computer_Vision_Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12W05i5K55HEVRDs2wy2aTvbPaOqpoi6S
"""

from google.colab import drive
drive.mount('/content/drive')

import cv2
import numpy as np
import PIL
from PIL import Image
import os

def enhance_image(image):
  Gray_Image=cv2.ctvcolor(image,cv2.COLOR_BGR2GRAY) #Image conversion
  clahe=cv2.createCLAHE(clipLimit=2.0,tileGridSize=(8,8))# Using histogram for imageconversion
  converted_image=clahe.apply(Gray_Image)
  return converted_image

def get_output_image(Input_image_path,fullyannoted_image_path,outputannoted_image_path):
    Input_image=cv2.imread(Input_image_path)
    fully_annoted_image=cv2.imread(fullyannoted_image_path)

    print("Shape of Input Image :" ,Input_image.shape)
    print("Shape of fully_annoted_image :",fully_annoted_image.shape)

    Resized_fully_annoted_image = cv2.resize(fully_annoted_image,(Input_image.shape[1],Input_image.shape[0])) # Image Resize
    Input_image_array = np.array(Input_image)
    fully_annoted_image_array = np.array(Resized_fully_annoted_image)

    # Seperating both left and right side of the image

    width = fully_annoted_image.shape[1]
    left_part = fully_annoted_image_array[:,:width//2,:]
    right_part = fully_annoted_image_array[:,width//2:,:]

    # ROF Calculation

    total_pixels = fully_annoted_image_array.shape[0] * fully_annoted_image_array.shape[1]
    foreground_pixels = np.count_nonzero(fully_annoted_image_array)
    rof = foreground_pixels / total_pixels
    print("Rate of ForeGround :",rof)

    #Copying Annoted Image to Original Image

    annoted_image = right_part if rof > 0.5 else left_part
    Input_image_array[:,width//2:,:] = annoted_image

    output_image = cv2.cvtColor(Input_image_array,cv2.COLOR_BGR2RGB)
    cv2.imwrite(outputannoted_image_path,output_image)

Input_image_path ='/content/drive/MyDrive/Colab Notebooks/original_image.jpg'

fullyannoted_image_path = '/content/drive/MyDrive/Colab Notebooks/fully_annotated_image.jpg'

outputannoted_image_path = '/content/drive/MyDrive/Colab Notebooks/OUTPUT_partially_annotated_image.jpg'

get_output_image(Input_image_path,fullyannoted_image_path,outputannoted_image_path)

image=("/content/drive/MyDrive/Colab Notebooks/original_image.jpg")
enhance_image(image)